//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#initialize_my_state_ix_data;
  pub(crate) mod r#my_program_error;
  pub(crate) mod r#state;

  pub use self::r#initialize_my_state_ix_data::*;
  pub use self::r#my_program_error::*;
  pub use self::r#state::*;

